### ISSUE TITLE
Typo in the API Documentation

### ISSUE THREAD

**Issue by pachevalier** [Widukind/widukind-api#7]
In the Datasets section of [Widukind API](http://widukind-api.cepremap.org/), there is a typo. It should be : 

    /dataset/<dataset> 	One Dataset

instead of 

    /datasets/<dataset> 	One Dataset

**Comment by srault95** [comment]
thank you.

**Comment by pachevalier** [comment]
I've got the impression that it's more a problem of consistency. For instance, if you want to get values of a dataset, you have to put ["datasets"]("http://widukind-api.cepremap.org/api/v1/json/datasets/insee-act-trim-anc/values") but if you want to get the frequencies, you have to write ["dataset"](http://widukind-api.cepremap.org/api/v1/json/dataset/insee-act-trim-anc/frequencies).
